### ISSUE TITLE
Javacript and python using lua output by default

### ISSUE THREAD

**Issue by tonycsoka** [tjdevries/present.nvim#4]
https://github.com/tjdevries/present.nvim/blob/4e500a14e343f21124525566af483ad48a1bae05/lua/present.lua#L72
https://github.com/tjdevries/present.nvim/blob/4e500a14e343f21124525566af483ad48a1bae05/lua/present.lua#L73

Great series TJ. Merry Xmas

**Comment by tjdevries** [comment]
Closed by #5
